### ISSUE TITLE
clean up: gradle

### ISSUE THREAD

**Issue by davidkhala** [Hyperledger-TWGC/java-gm#15]
我发现有一个gradle jar放在代码当中，它是必要的么？

**Comment by SamYuan1990** [comment]
ref https://docs.microsoft.com/zh-cn/azure/devops/pipelines/tasks/build/gradle?view=azure-devops#how-do-i-generate-a-wrapper-from-my-gradle-project
@davidkhala , request close this issue.

**Comment by davidkhala** [comment]
了解，看来是Azure没有好的gradle支持
