### ISSUE TITLE
update azp for release.

### ISSUE THREAD

**Issue by SamYuan1990** [Hyperledger-TWGC/java-gm#20]
Hi @davidkhala ,

could you please ref doc here for update azp for jar file release?
https://docs.microsoft.com/zh-cn/azure/devops/pipelines/artifacts/maven?view=azure-devops

I can't see Artifacts tag with my azp premission.
![image](https://user-images.githubusercontent.com/7820992/96342035-e3baae80-10cb-11eb-85b3-2f9d4bdfac9d.png)

**Comment by davidkhala** [comment]
确定发AZP不发github packages么？AZP看起会没那么直观

**Comment by davidkhala** [comment]
Azure 发布目标在Azure Artifacts上，还需要启动这个功能才能看到这个栏目

**Comment by SamYuan1990** [comment]
> 确定发Azure不发github packages么？Azure看起会没那么直观

能帮忙朝霞github package的有关link么？
我是希望java-gm的发布能够让java developer通过mvn/gradle这样的主流package管理工具下载下来的。
而不是手工倒入jar的依赖到项目里。

**Comment by davidkhala** [comment]
发布的是在[这里](https://docs.github.com/en/free-pro-team@latest/actions/guides/publishing-java-packages-with-maven#publishing-packages-to-github-packages)
使用的教程在[这里](https://docs.github.com/en/free-pro-team@latest/packages/using-github-packages-with-your-projects-ecosystem/configuring-gradle-for-use-with-github-packages)

**Comment by SamYuan1990** [comment]
> 发布的是在[这里](https://docs.github.com/en/free-pro-team@latest/actions/guides/publishing-java-packages-with-maven#publishing-packages-to-github-packages)
> 使用的教程在[这里](https://docs.github.com/en/free-pro-team@latest/packages/using-github-packages-with-your-projects-ecosystem/configuring-gradle-for-use-with-github-packages)

我理解这样的话github action是使用github的ci吧，可能就是两个pipeline了。没关系嘛这样？

**Comment by SamYuan1990** [comment]
@davidkhala , 另外你知道如何添加组织的pkg包么？

**Comment by davidkhala** [comment]
@SamYuan1990 组织上好像不能放pkg包吧。
在Azure Pipeline上发布github pkg原则上也可以的，把credential放进Azure Vault就行

**Comment by SamYuan1990** [comment]
> @SamYuan1990 组织上好像不能放pkg包吧。
> 在Azure Pipeline上发布github pkg原则上也可以的，把credential放进Azure Vault就行

https://github.com/Hyperledger-TWGC/java-gm/issues/20#issuecomment-711037551

你这两条comments给我看糊涂了。

**Comment by davidkhala** [comment]
> > @SamYuan1990 组织上好像不能放pkg包吧。
> > 在Azure Pipeline上发布github pkg原则上也可以的，把credential放进Azure Vault就行
> 
> [#20 (comment)](https://github.com/Hyperledger-TWGC/java-gm/issues/20#issuecomment-711037551)
> 
> 你这两条comments给我看糊涂了。

我的意思是对于Azure来说，Azure自己的DevOps全家桶里面有一个Artifact功能可以放发布包。
但是在pipeline里面通过纯脚本，也可以发布到github package上。但是如果要发布到github package，那么脚本里面需要一个github token才可以

**Comment by SamYuan1990** [comment]
> > > @SamYuan1990 组织上好像不能放pkg包吧。
> > > 在Azure Pipeline上发布github pkg原则上也可以的，把credential放进Azure Vault就行
> > 
> > 
> > [#20 (comment)](https://github.com/Hyperledger-TWGC/java-gm/issues/20#issuecomment-711037551)
> > 你这两条comments给我看糊涂了。
> 
> 我的意思是对于Azure来说，Azure自己的DevOps全家桶里面有一个Artifact功能可以放发布包。
> 但是在pipeline里面通过纯脚本，也可以发布到github package上。但是如果要发布到github package，那么脚本里面需要一个github token才可以

脚本里怎么可能公开存放github token啊。。。

**Comment by davidkhala** [comment]
> > > > @SamYuan1990 组织上好像不能放pkg包吧。
> > > > 在Azure Pipeline上发布github pkg原则上也可以的，把credential放进Azure Vault就行
> > > 
> > > 
> > > [#20 (comment)](https://github.com/Hyperledger-TWGC/java-gm/issues/20#issuecomment-711037551)
> > > 你这两条comments给我看糊涂了。
> > 
> > 
> > 我的意思是对于Azure来说，Azure自己的DevOps全家桶里面有一个Artifact功能可以放发布包。
> > 但是在pipeline里面通过纯脚本，也可以发布到github package上。但是如果要发布到github package，那么脚本里面需要一个github token才可以
> 
> 脚本里怎么可能公开存放github token啊。。。

所以我之前说使用Azure Vault的功能在平台上托管一个github token，在脚本里面通过上下文来引用

**Comment by SamYuan1990** [comment]
> > > > > @SamYuan1990 组织上好像不能放pkg包吧。
> > > > > 在Azure Pipeline上发布github pkg原则上也可以的，把credential放进Azure Vault就行
> > > > 
> > > > 
> > > > [#20 (comment)](https://github.com/Hyperledger-TWGC/java-gm/issues/20#issuecomment-711037551)
> > > > 你这两条comments给我看糊涂了。
> > > 
> > > 
> > > 我的意思是对于Azure来说，Azure自己的DevOps全家桶里面有一个Artifact功能可以放发布包。
> > > 但是在pipeline里面通过纯脚本，也可以发布到github package上。但是如果要发布到github package，那么脚本里面需要一个github token才可以
> > 
> > 
> > 脚本里怎么可能公开存放github token啊。。。
> 
> 所以我之前说使用Azure Vault的功能在平台上托管一个github token，在脚本里面通过上下文来引用

en... 可以研究研究，不过github package的空间怎么申请啊？

**Comment by davidkhala** [comment]
> > > > > > @SamYuan1990 组织上好像不能放pkg包吧。
> > > > > > 在Azure Pipeline上发布github pkg原则上也可以的，把credential放进Azure Vault就行
> > > > > 
> > > > > 
> > > > > [#20 (comment)](https://github.com/Hyperledger-TWGC/java-gm/issues/20#issuecomment-711037551)
> > > > > 你这两条comments给我看糊涂了。
> > > > 
> > > > 
> > > > 我的意思是对于Azure来说，Azure自己的DevOps全家桶里面有一个Artifact功能可以放发布包。
> > > > 但是在pipeline里面通过纯脚本，也可以发布到github package上。但是如果要发布到github package，那么脚本里面需要一个github token才可以
> > > 
> > > 
> > > 脚本里怎么可能公开存放github token啊。。。
> > 
> > 
> > 所以我之前说使用Azure Vault的功能在平台上托管一个github token，在脚本里面通过上下文来引用
> 
> en... 可以研究研究，不过github package的空间怎么申请啊？

默认就是开放的，不需要特定打开
