### ISSUE TITLE
add support/test sample for different hash function

### ISSUE THREAD

**Issue by SamYuan1990** [Hyperledger-TWGC/java-gm#35]
1.2.156.10197.1.501 SM2Sign-with-SM3
1.2.156.10197.1.502 SM2Sign-with-SHA1
1.2.156.10197.1.503 SM2Sign-with-SHA256
1.2.156.10197.1.504 SM2Sign-with-SHA511
1.2.156.10197.1.505 SM2Sign-with-SHA224
1.2.156.10197.1.506 SM2Sign-with-SHA384
1.2.156.10197.1.507 SM2Sign-with-RMD160

@davidkhala , do we need add sample for above all?

**Comment by davidkhala** [comment]
limited to use following only, close
`1.2.156.10197.1.501 SM2Sign-with-SM3`
