### ISSUE TITLE
some advise with sm3util and sm2util

### ISSUE THREAD

**Issue by Gsealy** [Hyperledger-TWGC/java-gm#36]
without JCE, dont need init BC provider
https://github.com/Hyperledger-TWGC/java-gm/blob/5b5f58eae3f5c9070d4d4c7981ecc8158fbcaea1/src/main/java/SM3Util.java#L18-L20

sm2 en/decrypt use which append mode? C1|C2|C3 or C1|C3|C2
https://github.com/Hyperledger-TWGC/java-gm/blob/5b5f58eae3f5c9070d4d4c7981ecc8158fbcaea1/src/main/java/SM2Util.java#L106

relate:
https://github.com/bcgit/bc-java/issues/478
https://github.com/bcgit/bc-java/commit/bda04fc807b206bd3162e78fb1027e8d077301ef

**Comment by davidkhala** [comment]
Thanks for raise up this interesting issue.
Is it related to this? https://cloud.tencent.com/developer/article/1605908

**Comment by SamYuan1990** [comment]
em.... for sm2, from my point of view, we'd better use default, so the code will upgrade with BC.

https://github.com/bcgit/bc-java/blob/bda04fc807b206bd3162e78fb1027e8d077301ef/core/src/main/java/org/bouncycastle/crypto/engines/SM2Engine.java#L55

and it is a good founding, we can adding supports for the mode for sm2.

**Comment by Gsealy** [comment]
> Thanks for raise up this interesting issue.
> Is it related to this? https://cloud.tencent.com/developer/article/1605908

ahh, cant see link in comment.. refer can see it

**Comment by Gsealy** [comment]
> em.... for sm2, from my point of view, we'd better use default, so the code will upgrade with BC.

but default mode was modified in official standard.[sm2 Public key encryption algorithm](http://openstd.samr.gov.cn/bzgk/gb/newGbInfo?hcno=370AF152CB5CA4A377EB4D1B21DECAE0)

**Comment by SamYuan1990** [comment]
> > em.... for sm2, from my point of view, we'd better use default, so the code will upgrade with BC.
> 
> but default mode was modified in official standard.[sm2 Public key encryption algorithm](http://openstd.samr.gov.cn/bzgk/gb/newGbInfo?hcno=370AF152CB5CA4A377EB4D1B21DECAE0)

some correction,
1. from point of view from interface design, we should add this support.
2. from point of view as dependency management,  the default mode will keep same with BC.

which means, I would like to change the code as BC did.
https://github.com/bcgit/bc-java/blob/r1rv68/core/src/main/java/org/bouncycastle/crypto/engines/SM2Engine.java#L43-L66

an interface and a method variable maybe.

the mode was modified, and personally I hope you are able to ask BC to make the change.
Plan A:java-gm depends on BC to create SM2 xxxx in xxx mode.
but not 
Plan B:java-gm has it own logic and base on BC to create SM2 xxxx in xxx mode.

For Plan A, when BC upgrade, java-gm can just use latest BC code without any code change.
For Plan B, java-gm should and will monitoring any changes in BC for sm2 and change the code ....

**Comment by Gsealy** [comment]
yes, default mode can keep same with BC. And add another method for other mode.

**Comment by SamYuan1990** [comment]
@Gsealy , em... what's your point with sm3util?

**Comment by davidkhala** [comment]
My opinion about mode support in java-gm is allow C1C3C2 only, although I see some SM2Engine constructor use C1C2C3 as default.

**Comment by Gsealy** [comment]
> @Gsealy , em... what's your point with sm3util?

use `SM3Digest` constructor lightweight api, don't need involve BC provider (`Security.addProvider()`)

if use `MessageDigest.getInstance("SM3", "BC")`,  need add this code

**Comment by SamYuan1990** [comment]
> My opinion about mode support in java-gm is to adopt C1C3C2 only, although I see some SM2Engine constructor use C1C2C3 as default.

see my comments above.

**Comment by SamYuan1990** [comment]
> > @Gsealy , em... what's your point with sm3util?
> 
> use `SM3Digest` constructor lightweight api, don't need involve BC provider (`Security.addProvider()`)
> 
> if use `MessageDigest.getInstance("SM3", "BC")`, need add this code

https://github.com/Hyperledger-TWGC/java-gm/blob/5b5f58eae3f5c9070d4d4c7981ecc8158fbcaea1/src/main/java/SM3Util.java#L29

you mean we don't need `Security.addProvider()` right?
