### ISSUE TITLE
SM4Util重构后的问题

### ISSUE THREAD

**Issue by xiaohui249** [Hyperledger-TWGC/java-gm#45]
看了synchronized同步代码，以及SM4Util的公开构造方法。我的想法：1、改成synchronized，目的应该是避免一个SM4Util单实例使用出现线程安全问题，但是影响了性能，而且并没有从实质上解决线程安全问题，线程安全问题是由Cipher引起的，而Cipher对象是公用的，无法保证调用者单例使用；2、SM4Util的构造方法是public的，所以从这个层面来讲，上一步的synchronized意义不大，而且实例化SM4Util时，Cipher.getInstance仍然要执行一遍。

**Comment by davidkhala** [comment]
是否需要回滚 #42 ？

**Comment by SamYuan1990** [comment]
先hold一下，@xiaohui249, 有何高见？
在我看来首先#42里有sm2/3的同步，目前大家对sm2/3的线程安全实现达成共识，没问题。
对于sm4，在我看来，鉴于sm4采用了和sm2一样/类似的线程安全测试逻辑。
如果有问题，那么sm4的测试是如何通过的？ sm2的测试是否需要更新？

**Comment by xiaohui249** [comment]
最后采用commons-pool来实现Cipher池，即解决了线程安全问题，也解决了每次实例化的性能开销问题。
