### ISSUE TITLE
azp ci badge显示没跑

### ISSUE THREAD

**Issue by SamYuan1990** [Hyperledger-TWGC/java-gm#48]

**Comment by davidkhala** [comment]
我猜测是因为最近的CI都是由PR触发的，反而直接在master brannch上push的commit没有，而readme的badge对应的是master branch的。
我手动在master上触发了一次，看看结束后会不会有badge更新

**Comment by davidkhala** [comment]
现在应该好了，也借此机会我们可以加一个schedule trigger
