### ISSUE TITLE
[提议] 支持通过直接读取公私钥字符串来加载其对象

### ISSUE THREAD

**Issue by photowey** [Hyperledger-TWGC/java-gm#81]
提议描述:
    通常有些场景是将公私钥配置在配置文件或者配置中心里面,这个时候我们的工具类似乎就有点力不从心,当然可以自己实现。

例子:
加载公钥:
> `twgc.gm.sm2.SM2Util#loadPublicFromFile`
```java
    public static PublicKey loadPublicFromFile(String filename) throws IOException, NoSuchProviderException, NoSuchAlgorithmException, InvalidKeySpecException {
        try (PemReader pemReader = new PemReader(new FileReader(filename))) {
            PemObject spki = pemReader.readPemObject();
            Security.getProvider(BouncyCastleProvider.PROVIDER_NAME);
            return KeyFactory.getInstance(Const.EC_VALUE, BouncyCastleProvider.PROVIDER_NAME).generatePublic(new X509EncodedKeySpec(spki.getContent()));
        }
    }
```

期望:
```java
// 提供类似的方法可以通过读取字符串来加载
PemReader pemReader = new PemReader(new StringReader(publicKey))
```

**Comment by SamYuan1990** [comment]
https://github.com/Hyperledger-TWGC/java-gm/blob/master/src/main/java/twgc/gm/sm2/SM2Util.java#L207 ?

**Comment by photowey** [comment]
1.`twgc.gm.sm2.SM2Util#loadPublicFromFile` 该方法的入参是一个文件名称(`filename`),然后构造一个`FileReader` 对象.
1.1.示例:
```java
new FileReader(filename)
```

2.期望
2.1.入参是密钥的字符串形式.
2.2.我们可以构造一个 `String` 类型 的 `Reader`
2.3.示例
```java
new StringReader(publicKey)
```

3.在 `2` 的基础上，我们可以直接从配置文件或者配置中心获取密钥对配置的字符串形式
3.1.通过直接读取字符串来构造其对象形式,比如: `PublicKey`

**Comment by SamYuan1990** [comment]
> 1.`twgc.gm.sm2.SM2Util#loadPublicFromFile` 该方法的入参是一个文件名称(`filename`),然后构造一个`FileReader` 对象. 1.1.示例:
> 
> ```java
> new FileReader(filename)
> ```
> 
> 2.期望 2.1.入参是密钥的字符串形式. 2.2.我们可以构造一个 `String` 类型 的 `Reader` 2.3.示例
> 
> ```java
> new StringReader(publicKey)
> ```
> 
> 3.在 `2` 的基础上，我们可以直接从配置文件或者配置中心获取密钥对配置的字符串形式 3.1.通过直接读取字符串来构造其对象形式,比如: `PublicKey`

开个PR带着用例看看，主要我理解最后是要配置文件的。为什么不直接读文件？有那个库能解决文件到string的转化么？

**Comment by photowey** [comment]
发起了一个 `PR` 见 [`#82`](https://github.com/Hyperledger-TWGC/java-gm/pull/82)
- 简单的写了一下从字符串加载密钥对和证书的示例

**Comment by SamYuan1990** [comment]
> 回答: 为什么不直接读文件？ 1.通常在软件开发中会有不同的环境; 2.不同的环境配置文件不一样(也就是说: 密钥对不一样); 3.不同环境的密钥对特别是正式环境(生产环境)的证书不可能放在项目中,更不可能放在服务器的某个目录; 4.所以通过字符串形式的配置就应运而生, 4.1.运维小伙伴可以在打包前修改不同环境的配置文件也就是密钥对; 4.2.程序也可以直接从 **配置中心** 中获取; 5.正因为上述的一些原因,就萌生了从字符串加载对象的想法.
> 
> `PS`: 1.以上为个人想法; 2.在实际的开发过程中,开发者自己实现一下也不是难事儿. 3.`java-gm` 作为一个库,当然期望它全一点.

1. 请使用环境管理方式。
2. 文件名可以一样，来避免雪花环境。
3. 鉴于2不成立，故3作为2的延伸看起来似乎不必要？
4. 证书是签名后的公钥，不能放在服务器目录的理由看起来并不成立。

如果是私钥，私钥通过网络传输的方式看起来并不安全。故，从配置中心获取私钥也就是4.2的安全性并不由java-gm处理。
从文件获取私钥，可以假设私钥物理存储于某个文件上。（总会存在文件上吧？考虑重启，备份，灾备）

**Comment by SamYuan1990** [comment]
@davidkhala, @xiaohui249 对于私钥的网络传输怎么看？

**Comment by davidkhala** [comment]
@SamYuan1990 我理解这个issue的初衷只是希望将io readstream作为输入的一个函数抽象并暴露出来，然后将原来file io的函数重写成新函数的一个特例封装。如果我理解和issue作者初衷吻合的话，我个人支持这个想法

关于私钥/公钥的网络传输话题，我认为已经离题了。

另外我也不同意说这个库的只能受限于读配置文件，业界有很多流式或者运行时式的软件范式全程都没有文件，甚至不允许程序读盘。我评估中若要满足以上需求，代码的改动也不大，是值得去兼顾的

**Comment by SamYuan1990** [comment]
我们暂时先以 #82 的代码为主吧。
支持string io不算很难，但是我还是希望能找到一个配置中心直接下发私钥的例子。比如某开源项目的案例？

**Comment by davidkhala** [comment]
@SamYuan1990 github action 的secret就能作为环境变量直接注入代码。类似的secret管理方式应该在业界不少

**Comment by SamYuan1990** [comment]
fixed via #82
